// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_ErrorScreen = NULL;
lv_obj_t * ui_ErrorLogText2 = NULL;
lv_obj_t * ui_ErrorLogLabel2 = NULL;
// event funtions

// build funtions

void ui_ErrorScreen_screen_init(void)
{
    ui_ErrorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ErrorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ErrorLogText2 = lv_textarea_create(ui_ErrorScreen);
    lv_obj_set_width(ui_ErrorLogText2, 286);
    lv_obj_set_height(ui_ErrorLogText2, 299);
    lv_obj_set_x(ui_ErrorLogText2, 2);
    lv_obj_set_y(ui_ErrorLogText2, -32);
    lv_obj_set_align(ui_ErrorLogText2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ErrorLogText2, "Placeholder...");

    ui_ErrorLogLabel2 = lv_label_create(ui_ErrorScreen);
    lv_obj_set_width(ui_ErrorLogLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ErrorLogLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ErrorLogLabel2, 0);
    lv_obj_set_y(ui_ErrorLogLabel2, -208);
    lv_obj_set_align(ui_ErrorLogLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ErrorLogLabel2, "Error Log");

}

void ui_ErrorScreen_screen_destroy(void)
{
    if(ui_ErrorScreen) lv_obj_del(ui_ErrorScreen);

    // NULL screen variables
    ui_ErrorScreen = NULL;
    ui_ErrorLogText2 = NULL;
    ui_ErrorLogLabel2 = NULL;

}
