// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SimpleSpeedScreen = NULL;
lv_obj_t * ui_SpeedVal2 = NULL;
lv_obj_t * ui_SpeedBar2 = NULL;
lv_obj_t * ui_MPH_Label2 = NULL;
// event funtions

// build funtions

void ui_SimpleSpeedScreen_screen_init(void)
{
    ui_SimpleSpeedScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SimpleSpeedScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpeedVal2 = lv_label_create(ui_SimpleSpeedScreen);
    lv_obj_set_width(ui_SpeedVal2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedVal2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedVal2, 0);
    lv_obj_set_y(ui_SpeedVal2, -46);
    lv_obj_set_align(ui_SpeedVal2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedVal2, "100");
    lv_obj_set_style_text_font(ui_SpeedVal2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBar2 = lv_bar_create(ui_SimpleSpeedScreen);
    lv_bar_set_value(ui_SpeedBar2, 70, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBar2, 150);
    lv_obj_set_height(ui_SpeedBar2, 10);
    lv_obj_set_x(ui_SpeedBar2, 0);
    lv_obj_set_y(ui_SpeedBar2, -1);
    lv_obj_set_align(ui_SpeedBar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBar2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBar2, lv_color_hex(0x03FA41), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SpeedBar2, lv_color_hex(0xFD0707), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SpeedBar2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MPH_Label2 = lv_label_create(ui_SimpleSpeedScreen);
    lv_obj_set_width(ui_MPH_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPH_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPH_Label2, 0);
    lv_obj_set_y(ui_MPH_Label2, 32);
    lv_obj_set_align(ui_MPH_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPH_Label2, "MPH");
    lv_obj_set_style_text_font(ui_MPH_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_SimpleSpeedScreen_screen_destroy(void)
{
    if(ui_SimpleSpeedScreen) lv_obj_del(ui_SimpleSpeedScreen);

    // NULL screen variables
    ui_SimpleSpeedScreen = NULL;
    ui_SpeedVal2 = NULL;
    ui_SpeedBar2 = NULL;
    ui_MPH_Label2 = NULL;

}
