// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_TireScreen = NULL;
lv_obj_t * ui_Title1 = NULL;
lv_obj_t * ui_SpeedVal1 = NULL;
lv_obj_t * ui_SpeedBar1 = NULL;
lv_obj_t * ui_MPH_Label1 = NULL;
lv_obj_t * ui_TPTitle = NULL;
lv_obj_t * ui_FRTirePressureArc = NULL;
lv_obj_t * ui_FRTirePressureVal = NULL;
lv_obj_t * ui_FLTirePressureArc = NULL;
lv_obj_t * ui_FLTirePressureVal = NULL;
lv_obj_t * ui_BLTirePressureArc = NULL;
lv_obj_t * ui_BLTirePressureVal = NULL;
lv_obj_t * ui_BRTirePressureArc = NULL;
lv_obj_t * ui_BRTirePressureVal = NULL;
// event funtions

// build funtions

void ui_TireScreen_screen_init(void)
{
    ui_TireScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TireScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title1 = lv_label_create(ui_TireScreen);
    lv_obj_set_width(ui_Title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title1, 0);
    lv_obj_set_y(ui_Title1, -221);
    lv_obj_set_align(ui_Title1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title1, "Tire Management");

    ui_SpeedVal1 = lv_label_create(ui_TireScreen);
    lv_obj_set_width(ui_SpeedVal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedVal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedVal1, 0);
    lv_obj_set_y(ui_SpeedVal1, -180);
    lv_obj_set_align(ui_SpeedVal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedVal1, "100");
    lv_obj_set_style_text_font(ui_SpeedVal1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBar1 = lv_bar_create(ui_TireScreen);
    lv_bar_set_value(ui_SpeedBar1, 70, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBar1, 150);
    lv_obj_set_height(ui_SpeedBar1, 10);
    lv_obj_set_x(ui_SpeedBar1, 0);
    lv_obj_set_y(ui_SpeedBar1, -141);
    lv_obj_set_align(ui_SpeedBar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBar1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBar1, lv_color_hex(0x03FA41), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SpeedBar1, lv_color_hex(0xFD0707), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SpeedBar1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MPH_Label1 = lv_label_create(ui_TireScreen);
    lv_obj_set_width(ui_MPH_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPH_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPH_Label1, 0);
    lv_obj_set_y(ui_MPH_Label1, -113);
    lv_obj_set_align(ui_MPH_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPH_Label1, "MPH");
    lv_obj_set_style_text_font(ui_MPH_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TPTitle = lv_label_create(ui_TireScreen);
    lv_obj_set_width(ui_TPTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TPTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TPTitle, 5);
    lv_obj_set_y(ui_TPTitle, -71);
    lv_obj_set_align(ui_TPTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TPTitle, "Tire Pressure");

    ui_FRTirePressureArc = lv_arc_create(ui_TireScreen);
    lv_obj_set_width(ui_FRTirePressureArc, 81);
    lv_obj_set_height(ui_FRTirePressureArc, 80);
    lv_obj_set_x(ui_FRTirePressureArc, 67);
    lv_obj_set_y(ui_FRTirePressureArc, -16);
    lv_obj_set_align(ui_FRTirePressureArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_FRTirePressureArc, 70);

    lv_obj_set_style_arc_color(ui_FRTirePressureArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FRTirePressureArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_FRTirePressureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FRTirePressureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_FRTirePressureVal = lv_label_create(ui_FRTirePressureArc);
    lv_obj_set_width(ui_FRTirePressureVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRTirePressureVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRTirePressureVal, -1);
    lv_obj_set_y(ui_FRTirePressureVal, -3);
    lv_obj_set_align(ui_FRTirePressureVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRTirePressureVal, "50");

    ui_FLTirePressureArc = lv_arc_create(ui_TireScreen);
    lv_obj_set_width(ui_FLTirePressureArc, 81);
    lv_obj_set_height(ui_FLTirePressureArc, 80);
    lv_obj_set_x(ui_FLTirePressureArc, -49);
    lv_obj_set_y(ui_FLTirePressureArc, -15);
    lv_obj_set_align(ui_FLTirePressureArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_FLTirePressureArc, 70);

    lv_obj_set_style_arc_color(ui_FLTirePressureArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FLTirePressureArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_FLTirePressureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FLTirePressureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_FLTirePressureVal = lv_label_create(ui_FLTirePressureArc);
    lv_obj_set_width(ui_FLTirePressureVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FLTirePressureVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FLTirePressureVal, -1);
    lv_obj_set_y(ui_FLTirePressureVal, -3);
    lv_obj_set_align(ui_FLTirePressureVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FLTirePressureVal, "50");

    ui_BLTirePressureArc = lv_arc_create(ui_TireScreen);
    lv_obj_set_width(ui_BLTirePressureArc, 81);
    lv_obj_set_height(ui_BLTirePressureArc, 80);
    lv_obj_set_x(ui_BLTirePressureArc, -52);
    lv_obj_set_y(ui_BLTirePressureArc, 66);
    lv_obj_set_align(ui_BLTirePressureArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_BLTirePressureArc, 70);

    lv_obj_set_style_arc_color(ui_BLTirePressureArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BLTirePressureArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BLTirePressureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLTirePressureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BLTirePressureVal = lv_label_create(ui_BLTirePressureArc);
    lv_obj_set_width(ui_BLTirePressureVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLTirePressureVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLTirePressureVal, -1);
    lv_obj_set_y(ui_BLTirePressureVal, -3);
    lv_obj_set_align(ui_BLTirePressureVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLTirePressureVal, "50");

    ui_BRTirePressureArc = lv_arc_create(ui_TireScreen);
    lv_obj_set_width(ui_BRTirePressureArc, 81);
    lv_obj_set_height(ui_BRTirePressureArc, 80);
    lv_obj_set_x(ui_BRTirePressureArc, 67);
    lv_obj_set_y(ui_BRTirePressureArc, 65);
    lv_obj_set_align(ui_BRTirePressureArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_BRTirePressureArc, 70);

    lv_obj_set_style_arc_color(ui_BRTirePressureArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BRTirePressureArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BRTirePressureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BRTirePressureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BRTirePressureVal = lv_label_create(ui_BRTirePressureArc);
    lv_obj_set_width(ui_BRTirePressureVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BRTirePressureVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BRTirePressureVal, -1);
    lv_obj_set_y(ui_BRTirePressureVal, -3);
    lv_obj_set_align(ui_BRTirePressureVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BRTirePressureVal, "50");

}

void ui_TireScreen_screen_destroy(void)
{
    if(ui_TireScreen) lv_obj_del(ui_TireScreen);

    // NULL screen variables
    ui_TireScreen = NULL;
    ui_Title1 = NULL;
    ui_SpeedVal1 = NULL;
    ui_SpeedBar1 = NULL;
    ui_MPH_Label1 = NULL;
    ui_TPTitle = NULL;
    ui_FRTirePressureArc = NULL;
    ui_FRTirePressureVal = NULL;
    ui_FLTirePressureArc = NULL;
    ui_FLTirePressureVal = NULL;
    ui_BLTirePressureArc = NULL;
    ui_BLTirePressureVal = NULL;
    ui_BRTirePressureArc = NULL;
    ui_BRTirePressureVal = NULL;

}
