// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TIRESCREEN_H
#define UI_TIRESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TireScreen
extern void ui_TireScreen_screen_init(void);
extern void ui_TireScreen_screen_destroy(void);
extern lv_obj_t * ui_TireScreen;
extern lv_obj_t * ui_Title1;
extern lv_obj_t * ui_SpeedVal1;
extern lv_obj_t * ui_SpeedBar1;
extern lv_obj_t * ui_MPH_Label1;
extern lv_obj_t * ui_TPTitle;
extern lv_obj_t * ui_FRTirePressureArc;
extern lv_obj_t * ui_FRTirePressureVal;
extern lv_obj_t * ui_FLTirePressureArc;
extern lv_obj_t * ui_FLTirePressureVal;
extern lv_obj_t * ui_BLTirePressureArc;
extern lv_obj_t * ui_BLTirePressureVal;
extern lv_obj_t * ui_BRTirePressureArc;
extern lv_obj_t * ui_BRTirePressureVal;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

