// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ERRORSCREEN_H
#define UI_ERRORSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ErrorScreen
extern void ui_ErrorScreen_screen_init(void);
extern void ui_ErrorScreen_screen_destroy(void);
extern lv_obj_t * ui_ErrorScreen;
extern lv_obj_t * ui_ErrorLogText2;
extern lv_obj_t * ui_ErrorLogLabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

