// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_Title = NULL;
lv_obj_t * ui_SpeedVal = NULL;
lv_obj_t * ui_SpeedBar = NULL;
lv_obj_t * ui_MPH_Label = NULL;
lv_obj_t * ui_AccTempArc = NULL;
lv_obj_t * ui_AccTempValue = NULL;
lv_obj_t * ui_Accumulator_Title = NULL;
lv_obj_t * ui_ErrorLogText = NULL;
lv_obj_t * ui_ErrorLogLabel = NULL;
lv_obj_t * ui_BrakeBar = NULL;
lv_obj_t * ui_GasBar = NULL;
lv_obj_t * ui_GasLabel = NULL;
lv_obj_t * ui_BrakeLabel = NULL;
lv_obj_t * ui_BatteryArc = NULL;
lv_obj_t * ui_BatteryVal = NULL;
lv_obj_t * ui_BatteryTitle = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title, 0);
    lv_obj_set_y(ui_Title, -221);
    lv_obj_set_align(ui_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title, "Main Display");

    ui_SpeedVal = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_SpeedVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedVal, 0);
    lv_obj_set_y(ui_SpeedVal, -180);
    lv_obj_set_align(ui_SpeedVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedVal, "100");
    lv_obj_set_style_text_font(ui_SpeedVal, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_value(ui_SpeedBar, 70, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBar, 150);
    lv_obj_set_height(ui_SpeedBar, 10);
    lv_obj_set_x(ui_SpeedBar, 0);
    lv_obj_set_y(ui_SpeedBar, -141);
    lv_obj_set_align(ui_SpeedBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBar, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBar, lv_color_hex(0x03FA41), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SpeedBar, lv_color_hex(0xFD0707), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SpeedBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MPH_Label = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_MPH_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPH_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPH_Label, 0);
    lv_obj_set_y(ui_MPH_Label, -113);
    lv_obj_set_align(ui_MPH_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPH_Label, "MPH");
    lv_obj_set_style_text_font(ui_MPH_Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccTempArc = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_AccTempArc, 81);
    lv_obj_set_height(ui_AccTempArc, 80);
    lv_obj_set_x(ui_AccTempArc, -86);
    lv_obj_set_y(ui_AccTempArc, -25);
    lv_obj_set_align(ui_AccTempArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_AccTempArc, 70);

    lv_obj_set_style_arc_img_src(ui_AccTempArc, &ui_img_conical_gradient_2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AccTempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccTempArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AccTempValue = lv_label_create(ui_AccTempArc);
    lv_obj_set_width(ui_AccTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccTempValue, -1);
    lv_obj_set_y(ui_AccTempValue, -3);
    lv_obj_set_align(ui_AccTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccTempValue, "50°");

    ui_Accumulator_Title = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Accumulator_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Accumulator_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Accumulator_Title, -88);
    lv_obj_set_y(ui_Accumulator_Title, -80);
    lv_obj_set_align(ui_Accumulator_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Accumulator_Title, "Accumulator");

    ui_ErrorLogText = lv_textarea_create(ui_MainScreen);
    lv_obj_set_width(ui_ErrorLogText, 150);
    lv_obj_set_height(ui_ErrorLogText, 70);
    lv_obj_set_x(ui_ErrorLogText, -78);
    lv_obj_set_y(ui_ErrorLogText, 195);
    lv_obj_set_align(ui_ErrorLogText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ErrorLogText, "Placeholder...");

    ui_ErrorLogLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ErrorLogLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ErrorLogLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ErrorLogLabel, -78);
    lv_obj_set_y(ui_ErrorLogLabel, 139);
    lv_obj_set_align(ui_ErrorLogLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ErrorLogLabel, "Error Log");

    ui_BrakeBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_value(ui_BrakeBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BrakeBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BrakeBar, 150);
    lv_obj_set_height(ui_BrakeBar, 11);
    lv_obj_set_x(ui_BrakeBar, 151);
    lv_obj_set_y(ui_BrakeBar, 214);
    lv_obj_set_align(ui_BrakeBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrakeBar, lv_color_hex(0x6A6868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrakeBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_BrakeBar, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrakeBar, lv_color_hex(0xFC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrakeBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_GasBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_value(ui_GasBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_GasBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_GasBar, 150);
    lv_obj_set_height(ui_GasBar, 11);
    lv_obj_set_x(ui_GasBar, 189);
    lv_obj_set_y(ui_GasBar, 214);
    lv_obj_set_align(ui_GasBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_GasBar, lv_color_hex(0x6A6868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GasBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_GasBar, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GasBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GasBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_GasLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_GasLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GasLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GasLabel, 119);
    lv_obj_set_y(ui_GasLabel, 36);
    lv_obj_set_align(ui_GasLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GasLabel, "Gas");

    ui_BrakeLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BrakeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrakeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrakeLabel, 79);
    lv_obj_set_y(ui_BrakeLabel, 36);
    lv_obj_set_align(ui_BrakeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrakeLabel, "Brake");

    ui_BatteryArc = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_BatteryArc, 81);
    lv_obj_set_height(ui_BatteryArc, 80);
    lv_obj_set_x(ui_BatteryArc, 86);
    lv_obj_set_y(ui_BatteryArc, -25);
    lv_obj_set_align(ui_BatteryArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_BatteryArc, 70);

    lv_obj_set_style_arc_color(ui_BatteryArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BatteryArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BatteryArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BatteryVal = lv_label_create(ui_BatteryArc);
    lv_obj_set_width(ui_BatteryVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryVal, -1);
    lv_obj_set_y(ui_BatteryVal, -3);
    lv_obj_set_align(ui_BatteryVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryVal, "50%");

    ui_BatteryTitle = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BatteryTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryTitle, 88);
    lv_obj_set_y(ui_BatteryTitle, -80);
    lv_obj_set_align(ui_BatteryTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTitle, "Battery");

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_Title = NULL;
    ui_SpeedVal = NULL;
    ui_SpeedBar = NULL;
    ui_MPH_Label = NULL;
    ui_AccTempArc = NULL;
    ui_AccTempValue = NULL;
    ui_Accumulator_Title = NULL;
    ui_ErrorLogText = NULL;
    ui_ErrorLogLabel = NULL;
    ui_BrakeBar = NULL;
    ui_GasBar = NULL;
    ui_GasLabel = NULL;
    ui_BrakeLabel = NULL;
    ui_BatteryArc = NULL;
    ui_BatteryVal = NULL;
    ui_BatteryTitle = NULL;

}
