// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SIMPLESPEEDSCREEN_H
#define UI_SIMPLESPEEDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SimpleSpeedScreen
extern void ui_SimpleSpeedScreen_screen_init(void);
extern void ui_SimpleSpeedScreen_screen_destroy(void);
extern lv_obj_t * ui_SimpleSpeedScreen;
extern lv_obj_t * ui_SpeedVal2;
extern lv_obj_t * ui_SpeedBar2;
extern lv_obj_t * ui_MPH_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

