// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Title;
extern lv_obj_t * ui_SpeedVal;
extern lv_obj_t * ui_SpeedBar;
extern lv_obj_t * ui_MPH_Label;
extern lv_obj_t * ui_AccTempArc;
extern lv_obj_t * ui_AccTempValue;
extern lv_obj_t * ui_Accumulator_Title;
extern lv_obj_t * ui_ErrorLogText;
extern lv_obj_t * ui_ErrorLogLabel;
extern lv_obj_t * ui_BrakeBar;
extern lv_obj_t * ui_GasBar;
extern lv_obj_t * ui_GasLabel;
extern lv_obj_t * ui_BrakeLabel;
extern lv_obj_t * ui_BatteryArc;
extern lv_obj_t * ui_BatteryVal;
extern lv_obj_t * ui_BatteryTitle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

