// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Title;
extern lv_obj_t * ui_SpeedVal;
extern lv_obj_t * ui_SpeedBar;
extern lv_obj_t * ui_MPH_Label;
extern lv_obj_t * ui_TempArc;
extern lv_obj_t * ui_MPH_Label2;
extern lv_obj_t * ui_Accumulator_Title;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_SpeedBar1;
extern lv_obj_t * ui_SpeedBar2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

