// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Title = NULL;
lv_obj_t * ui_SpeedVal = NULL;
lv_obj_t * ui_SpeedBar = NULL;
lv_obj_t * ui_MPH_Label = NULL;
lv_obj_t * ui_TempArc = NULL;
lv_obj_t * ui_MPH_Label2 = NULL;
lv_obj_t * ui_Accumulator_Title = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_SpeedBar1 = NULL;
lv_obj_t * ui_SpeedBar2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title, 4);
    lv_obj_set_y(ui_Title, -222);
    lv_obj_set_align(ui_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title, "Test Display");

    ui_SpeedVal = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedVal, 7);
    lv_obj_set_y(ui_SpeedVal, -181);
    lv_obj_set_align(ui_SpeedVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedVal, "100");
    lv_obj_set_style_text_font(ui_SpeedVal, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_SpeedBar, 70, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBar, 150);
    lv_obj_set_height(ui_SpeedBar, 10);
    lv_obj_set_x(ui_SpeedBar, 9);
    lv_obj_set_y(ui_SpeedBar, -151);
    lv_obj_set_align(ui_SpeedBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBar, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBar, lv_color_hex(0x03FA41), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SpeedBar, lv_color_hex(0xFD0707), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SpeedBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MPH_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MPH_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPH_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPH_Label, 9);
    lv_obj_set_y(ui_MPH_Label, -125);
    lv_obj_set_align(ui_MPH_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPH_Label, "MPH");
    lv_obj_set_style_text_font(ui_MPH_Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempArc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_TempArc, 81);
    lv_obj_set_height(ui_TempArc, 80);
    lv_obj_set_x(ui_TempArc, -86);
    lv_obj_set_y(ui_TempArc, -28);
    lv_obj_set_align(ui_TempArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_TempArc, 70);

    lv_obj_set_style_arc_img_src(ui_TempArc, &ui_img_conical_gradient_2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MPH_Label2 = lv_label_create(ui_TempArc);
    lv_obj_set_width(ui_MPH_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPH_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPH_Label2, -1);
    lv_obj_set_y(ui_MPH_Label2, -3);
    lv_obj_set_align(ui_MPH_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPH_Label2, "50°");

    ui_Accumulator_Title = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Accumulator_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Accumulator_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Accumulator_Title, -88);
    lv_obj_set_y(ui_Accumulator_Title, -87);
    lv_obj_set_align(ui_Accumulator_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Accumulator_Title, "Accumulator");

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 150);
    lv_obj_set_height(ui_TextArea1, 70);
    lv_obj_set_x(ui_TextArea1, -79);
    lv_obj_set_y(ui_TextArea1, 116);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -82);
    lv_obj_set_y(ui_Label5, 63);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Error Log");

    ui_SpeedBar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_SpeedBar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBar1, 150);
    lv_obj_set_height(ui_SpeedBar1, 11);
    lv_obj_set_x(ui_SpeedBar1, 154);
    lv_obj_set_y(ui_SpeedBar1, 157);
    lv_obj_set_align(ui_SpeedBar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBar1, lv_color_hex(0x6A6868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_SpeedBar1, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBar1, lv_color_hex(0xFC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SpeedBar2 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_SpeedBar2, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBar2, 150);
    lv_obj_set_height(ui_SpeedBar2, 11);
    lv_obj_set_x(ui_SpeedBar2, 183);
    lv_obj_set_y(ui_SpeedBar2, 159);
    lv_obj_set_align(ui_SpeedBar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBar2, lv_color_hex(0x6A6868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_SpeedBar2, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBar2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 117);
    lv_obj_set_y(ui_Label1, -9);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Gas");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 78);
    lv_obj_set_y(ui_Label2, -8);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Brake");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Title = NULL;
    ui_SpeedVal = NULL;
    ui_SpeedBar = NULL;
    ui_MPH_Label = NULL;
    ui_TempArc = NULL;
    ui_MPH_Label2 = NULL;
    ui_Accumulator_Title = NULL;
    ui_TextArea1 = NULL;
    ui_Label5 = NULL;
    ui_SpeedBar1 = NULL;
    ui_SpeedBar2 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;

}
